version: "3"
services: 
  mq:
    image: rabbitmq:3-management
    environment: 
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports: 
      - "15672:15672"
      - "5672:5672"